(function(g){var window=this;var uHa=function(a,b){a.xa("onAutonavCoundownStarted",b)},p3=function(a,b,c){var d=b.Na();
g.O(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.te(c?c:"mqdefault.jpg");var f=null,h=null;b instanceof g.wH&&(b.lengthText?(f=b.lengthText||null,h=b.ku||null):b.lengthSeconds&&(f=g.EL(b.lengthSeconds),h=g.EL(b.lengthSeconds,!0)));var l=!!e;e=l&&"RD"===(new g.ZM(e.substr(0,2),e.substr(2))).type;var m=b instanceof g.wH?b.isLivePlayback:null,n=b instanceof g.wH?b.isUpcoming:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:
b.author,aria_label:b.gq||g.AJ("Watch $TITLE",{TITLE:b.title}),duration:f,timestamp:h,url:b.rl(),is_live:m,is_upcoming:n,is_list:l,is_mix:e,background:c?"background-image: url("+c+")":"",views_and_publish_time:d.shortViewCount?d.shortViewCount+" \u2022 "+d.publishedTimeText:d.publishedTimeText,autoplayAlternativeHeader:b.jq};b instanceof g.$M&&(d.playlist_length=b.length);a.update(d)},q3=function(a){var b=a.T(),c=b.l;
g.X.call(this,{D:"a",K:"ytp-autonav-suggestion-card",U:{href:"{{url}}",target:c?b.C:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},S:[{D:"div",ka:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],U:{style:"{{background}}"},S:[{D:"div",U:{"aria-label":"{{timestamp}}"},ka:["ytp-autonav-timestamp"],ba:"{{duration}}"},{D:"div",ka:["ytp-autonav-live-stamp"],ba:"Live"},{D:"div",
ka:["ytp-autonav-upcoming-stamp"],ba:"Upcoming"},{D:"div",K:"ytp-autonav-list-overlay",S:[{D:"div",K:"ytp-autonav-mix-text",ba:"Mix"},{D:"div",K:"ytp-autonav-mix-icon"}]}]},{D:"div",ka:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],ba:"{{title}}"},{D:"div",ka:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],ba:"{{author}}"},{D:"div",ka:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],ba:"{{views_and_publish_time}}"}]});this.G=a;this.suggestion=
null;this.i=c;this.ya("click",this.onClick);this.ya("keypress",this.l)},s3=function(a,b){b=void 0===b?!1:b;
g.X.call(this,{D:"div",K:"ytp-autonav-endscreen-countdown-container"});var c=this;this.C=b;this.l=0;var d=a.T(),e=d.l;this.G=a;this.suggestion=null;this.i=new g.X({D:"div",K:"ytp-autonav-endscreen-upnext-container",U:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},S:[{D:"div",K:"ytp-autonav-endscreen-upnext-header"},{D:"div",K:"ytp-autonav-endscreen-upnext-alternative-header",ba:"{{autoplayAlternativeHeader}}"},
{D:"a",K:"ytp-autonav-endscreen-link-container",U:{href:"{{url}}",target:e?d.C:""},S:[{D:"div",K:"ytp-autonav-endscreen-upnext-thumbnail",U:{style:"{{background}}"},S:[{D:"div",U:{"aria-label":"{{timestamp}}"},ka:["ytp-autonav-timestamp"],ba:"{{duration}}"},{D:"div",ka:["ytp-autonav-live-stamp"],ba:"Live"},{D:"div",ka:["ytp-autonav-upcoming-stamp"],ba:"Upcoming"}]},{D:"div",K:"ytp-autonav-endscreen-video-info",S:[{D:"div",K:"ytp-autonav-endscreen-premium-badge"},{D:"div",K:"ytp-autonav-endscreen-upnext-title",
ba:"{{title}}"},{D:"div",K:"ytp-autonav-endscreen-upnext-author",ba:"{{author}}"},{D:"div",K:"ytp-autonav-view-and-date",ba:"{{views_and_publish_time}}"},{D:"div",K:"ytp-autonav-author-and-view",ba:"{{author_and_views}}"}]}]}]});g.I(this,this.i);this.i.fa(this.element);e||this.N(this.i.ha("ytp-autonav-endscreen-link-container"),"click",this.GB);this.G.Hb(this.element,this,115127);this.G.Hb(this.i.ha("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.X({D:"div",K:"ytp-autonav-overlay"});
g.I(this,this.overlay);this.overlay.fa(this.element);this.u=new g.X({D:"div",K:"ytp-autonav-endscreen-button-container"});g.I(this,this.u);this.u.fa(this.element);this.cancelButton=new g.X({D:"button",ka:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button"],U:{"aria-label":"Cancel autoplay"},ba:"Cancel"});g.I(this,this.cancelButton);this.cancelButton.fa(this.u.element);this.cancelButton.ya("click",this.wJ,this);this.G.Hb(this.cancelButton.element,this,115129);this.playButton=
new g.X({D:"a",ka:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button"],U:{href:"{{url}}",role:"button","aria-label":"Play next video"},ba:"Play Now"});g.I(this,this.playButton);this.playButton.fa(this.u.element);this.playButton.ya("click",this.GB,this);this.G.Hb(this.playButton.element,this,115130);this.B=new g.M(function(){r3(c)},500);
g.I(this,this.B);this.FB();this.N(a,"autonavvisibility",this.FB)},r3=function(a){var b=t3(a),c=Math.min(a.l?Date.now()-a.l:0,b);
u3(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Og()?a.select(!0):a.Og()&&a.B.start()},t3=function(a){var b=a.G.Wm();
return 0<=b?b:g.S(a.G.T().experiments,"autoplay_time")||1E4},u3=function(a,b){b=void 0===b?-1:b;
var c=a.i.ha("ytp-autonav-endscreen-upnext-header");g.Ke(c);if(0<=b){var d=String(b),e="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],f="Up next in $SECONDS".indexOf(e);if(0<=f){c.appendChild(g.Je("Up next in $SECONDS".slice(0,f)));var h=g.Ie("span");g.jn(h,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Qe(h,d);c.appendChild(h);c.appendChild(g.Je("Up next in $SECONDS".slice(f+e.length)));return}}g.Qe(c,"Up next")},v3=function(a,b){g.X.call(this,{D:"div",
ka:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},x3=function(a){g.X.call(this,{D:"div",
ka:["ytp-upnext","ytp-player-content"],U:{"aria-label":"{{aria_label}}"},S:[{D:"div",K:"ytp-cued-thumbnail-overlay-image",U:{style:"{{background}}"}},{D:"span",K:"ytp-upnext-top",S:[{D:"span",K:"ytp-upnext-header",ba:"Up Next"},{D:"span",K:"ytp-upnext-title",ba:"{{title}}"},{D:"span",K:"ytp-upnext-author",ba:"{{author}}"}]},{D:"a",K:"ytp-upnext-autoplay-icon",U:{role:"button",href:"{{url}}","aria-label":"Play next video"},S:[{D:"svg",U:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
S:[{D:"circle",K:"ytp-svg-autoplay-circle",U:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",K:"ytp-svg-autoplay-ring",U:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",K:"ytp-svg-fill",U:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",K:"ytp-upnext-bottom",S:[{D:"span",K:"ytp-upnext-cancel"},{D:"span",K:"ytp-upnext-paused",
ba:"Autoplay is paused"}]}]});this.api=a;this.cancelButton=null;this.C=this.ha("ytp-svg-autoplay-ring");this.u=this.notification=this.i=this.suggestion=null;this.B=new g.M(this.mt,5E3,this);this.l=0;var b=this.ha("ytp-upnext-cancel");this.cancelButton=new g.X({D:"button",ka:["ytp-upnext-cancel-button","ytp-button"],U:{tabindex:"0","aria-label":"Cancel autoplay"},ba:"Cancel"});g.I(this,this.cancelButton);this.cancelButton.ya("click",this.xJ,this);this.cancelButton.fa(b);this.cancelButton&&this.api.Hb(this.cancelButton.element,
this,115129);g.I(this,this.B);this.api.Hb(this.element,this,18788);b=this.ha("ytp-upnext-autoplay-icon");this.N(b,"click",this.yJ);this.api.Hb(b,this,115130);this.HB();this.N(a,"autonavvisibility",this.HB);this.N(a,"mdxnowautoplaying",this.QN);this.N(a,"mdxautoplaycanceled",this.RN);this.N(a,"mdxautoplayupnext",this.vH);w3(this)&&(a=(a=g.RM(this.api.Ua()))?a.mL():null)&&this.vH(a);g.O(this.element,"ytp-upnext-mobile",this.api.T().i)},w3=function(a){return 3===a.api.getPresentingPlayerType()},vHa=
function(a,b){return b?b:0<=a.api.Wm()?a.api.Wm():g.S(a.api.T().experiments,"autoplay_time")||1E4},y3=function(a,b){var c=vHa(a,b),d=Math,e=d.min;
var f=(0,g.Q)()-a.l;d=e.call(d,f,c);c=0===c?1:Math.min(d/c,1);a.C.setAttribute("stroke-dashoffset",""+-211*(c+1));1<=c&&a.Og()&&!w3(a)?a.select(!0):a.Og()&&a.i.start()},z3=function(a){v3.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=this.suggestions=null;this.table=new g.X({D:"div",K:"ytp-suggestion-panel",S:[{D:"div",ka:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],ba:"More videos"}]});this.J=new g.X({D:"div",K:"ytp-suggestions-container"});this.videos=[];this.u=null;this.C=this.I=!1;this.l=new s3(this.player);g.I(this,this.l);this.l.fa(this.element);a.getVideoData().wc?this.i=this.l:(this.i=new x3(a),g.VM(this.player,this.i.element,4),g.I(this,this.i));this.overlay=
new g.X({D:"div",K:"ytp-autonav-overlay-cancelled-state"});g.I(this,this.overlay);this.overlay.fa(this.element);this.B=new g.XM(this);g.I(this,this.B);g.I(this,this.table);this.table.fa(this.element);this.table.show();g.I(this,this.J);this.J.fa(this.table.element);this.hide()},wHa=function(a,b){return g.Qc(b.suggestions,function(c){c=g.sP(a.player.T(),c);
g.I(a,c);return c})},A3=function(a){var b=a.wd();
b!==a.C&&(a.C=b,a.player.V("autonavvisibility"),a.C?(a.l!==a.i&&a.l.hide(),a.table.hide()):(a.l!==a.i&&a.l.show(),a.table.show()))},B3=function(a){v3.call(this,a,"subscribecard-endscreen");
this.i=new g.X({D:"div",K:"ytp-subscribe-card",S:[{D:"img",K:"ytp-author-image",U:{src:"{{profilePicture}}"}},{D:"div",K:"ytp-subscribe-card-right",S:[{D:"div",K:"ytp-author-name",ba:"{{author}}"},{D:"div",K:"html5-subscribe-button-container"}]}]});g.I(this,this.i);this.i.fa(this.element);var b=a.getVideoData();this.subscribeButton=new g.fO("Subscribe",null,"Unsubscribe",null,!0,!1,b.Bg,b.subscribed,"trailer-endscreen",null,null,a);g.I(this,this.subscribeButton);this.subscribeButton.fa(this.i.ha("html5-subscribe-button-container"));
this.N(a,"videodatachange",this.wa);this.wa();this.hide()},C3=function(a){var b=a.T(),c=g.DA||g.pg?{style:"will-change: opacity"}:void 0,d=b.l,e=["ytp-videowall-still"];
b.i&&e.push("ytp-videowall-show-text");g.X.call(this,{D:"a",ka:e,U:{href:"{{url}}",target:d?b.C:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},S:[{D:"div",K:"ytp-videowall-still-image",U:{style:"{{background}}"}},{D:"span",K:"ytp-videowall-still-info",S:[{D:"span",K:"ytp-videowall-still-info-bg",S:[{D:"span",K:"ytp-videowall-still-info-content",U:c,S:[{D:"span",K:"ytp-videowall-still-info-title",ba:"{{title}}"},{D:"span",K:"ytp-videowall-still-info-author",
ba:"{{author_and_views}}"},{D:"span",K:"ytp-videowall-still-info-live",ba:"Live"},{D:"span",K:"ytp-videowall-still-info-duration",ba:"{{duration}}"}]}]}]},{D:"span",ka:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],S:[{D:"span",K:"ytp-videowall-still-listlabel-icon"},"Playlist",{D:"span",K:"ytp-videowall-still-listlabel-length",S:[" (",{D:"span",ba:"{{playlist_length}}"},")"]}]},{D:"span",ka:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],S:[{D:"span",
K:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{D:"span",K:"ytp-videowall-still-listlabel-length",ba:" (50+)"}]}]});this.suggestion=null;this.l=d;this.api=a;this.i=new g.XM(this);g.I(this,this.i);this.ya("click",this.onClick);this.ya("keypress",this.u);this.i.N(a,"videodatachange",this.Oa);a.Jg(this.element,this);this.Oa()},D3=function(a){v3.call(this,a,"videowall-endscreen");
var b=this;this.G=a;this.u=0;this.stills=[];this.B=this.videoData=this.suggestions=null;this.C=this.J=!1;this.L=null;this.l=new g.XM(this);g.I(this,this.l);this.I=new g.M(function(){g.N(b.element,"ytp-show-tiles")},0);
g.I(this,this.I);var c=new g.X({D:"button",ka:["ytp-button","ytp-endscreen-previous"],U:{"aria-label":"Previous"},S:[g.cL()]});g.I(this,c);c.fa(this.element);c.ya("click",this.CJ,this);this.table=new g.VK({D:"div",K:"ytp-endscreen-content"});g.I(this,this.table);this.table.fa(this.element);c=new g.X({D:"button",ka:["ytp-button","ytp-endscreen-next"],U:{"aria-label":"Next"},S:[g.dL()]});g.I(this,c);c.fa(this.element);c.ya("click",this.BJ,this);a.getVideoData().wc?this.i=new s3(a,!0):this.i=new x3(a);
g.I(this,this.i);g.VM(this.player,this.i.element,4);this.hide()},E3=function(a){return g.WM(a.player)&&a.iq()&&!a.B},xHa=function(a,b){return g.Qc(b.suggestions,function(c){c=g.sP(a.G.T(),c);
g.I(a,c);return c})},F3=function(a){var b=a.wd();
b!==a.J&&(a.J=b,a.player.V("autonavvisibility"))},G3=function(a){g.eN.call(this,a);
var b=this;this.endScreen=null;this.i=this.l=this.u=!1;this.listeners=new g.XM(this);g.I(this,this.listeners);this.env=a.T();yHa(a)?(this.u=!0,zHa(this),this.i?this.endScreen=new z3(a):this.endScreen=new D3(this.player)):this.env.Fc?this.endScreen=new B3(this.player):this.endScreen=new v3(this.player);g.I(this,this.endScreen);g.VM(this.player,this.endScreen.element,4);AHa(this);this.listeners.N(a,"videodatachange",this.Oa,this);this.listeners.N(a,g.AD("endscreen"),function(c){b.zd(c)});
this.listeners.N(a,g.BD("endscreen"),function(c){b.mf(c)})},zHa=function(a){var b=a.player.getVideoData();
if(!b||a.i===b.Ze&&a.l===b.wc)return!1;a.i=b.Ze;a.l=b.wc;return!0},yHa=function(a){a=a.T();
return a.ib&&!a.Fc},AHa=function(a){a.player.Oe("endscreen");
var b=a.player.getVideoData();b=new g.xD(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.xD(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});a.player.sd([b,c])};
g.OM.prototype.Wm=g.ca(4,function(){return this.app.Wm()});
g.$V.prototype.Wm=g.ca(3,function(){return this.getVideoData().IH});
g.u(q3,g.X);q3.prototype.select=function(){(this.G.Ai(this.suggestion.Na().videoId,this.suggestion.Cd,this.suggestion.getPlaylistId(),void 0,void 0,this.suggestion.Ix||void 0)||this.G.Z("web_player_endscreen_double_log_fix_killswitch"))&&this.G.ub(this.element)};
q3.prototype.onClick=function(a){g.xN(a,this.G,this.i,this.suggestion.Cd||void 0)&&this.select()};
q3.prototype.l=function(a){switch(a.keyCode){case 13:case 32:g.cp(a)||(this.select(),g.bp(a))}};
q3.prototype.Ud=function(a){g.O(this.element,"ytp-suggestion-card-with-margin",a)};g.u(s3,g.X);g.k=s3.prototype;g.k.Xp=function(a){this.suggestion!==a&&(this.suggestion=a,p3(this.i,a),this.playButton.Ba("url",this.suggestion.rl()),this.Ud())};
g.k.Ud=function(){var a=this.G.Vi(!0,this.G.isFullscreen());g.O(this.element,"ytp-autonav-endscreen-small-mode",this.Le(a));g.O(this.element,"ytp-autonav-endscreen-is-premium",!!this.suggestion&&!!this.suggestion.gv);g.O(this.G.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!this.G.wd());g.O(this.G.getRootNode(),"countdown-running",this.Og());g.O(this.element,"ytp-player-content",this.G.wd());g.mg(this.overlay.element,{width:a.width+"px"});if(!this.Og()){this.G.wd()?u3(this,Math.round(t3(this)/
1E3)):u3(this);a=!!this.suggestion&&!!this.suggestion.jq;var b=this.G.wd()||!a;g.O(this.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!b&&a);g.O(this.element,"ytp-autonav-endscreen-upnext-no-alternative-header",b&&!a);g.YK(this.u,this.G.wd())}};
g.k.Og=function(){return 0<this.l};
g.k.yp=function(){this.Og()||(this.l=Date.now(),r3(this),uHa(this.G,t3(this)),g.O(this.G.getRootNode(),"countdown-running",this.Og()))};
g.k.An=function(){this.vk();r3(this)};
g.k.vk=function(){this.Og()&&(this.B.stop(),this.l=0)};
g.k.select=function(a){this.G.nextVideo(!1,void 0===a?!1:a);this.vk()};
g.k.GB=function(a){g.xN(a,this.G)&&(a.currentTarget===this.playButton.element?this.G.ub(this.playButton.element):a.currentTarget===this.i.ha("ytp-autonav-endscreen-link-container")&&(a=this.i.ha("ytp-autonav-endscreen-link-container"),this.G.Qa(a,!0),this.G.ub(a)),this.select())};
g.k.wJ=function(){this.G.ub(this.cancelButton.element);g.QM(this.G,!0)};
g.k.FB=function(){var a=this.G.wd();this.C&&this.ab!==a&&g.YK(this,a);this.Ud();this.G.Qa(this.element,a);this.G.Qa(this.cancelButton.element,a);this.G.Qa(this.i.ha("ytp-autonav-endscreen-link-container"),a);this.G.Qa(this.playButton.element,a)};
g.k.Le=function(a){return 400>a.width||459>a.height};g.u(v3,g.X);g.k=v3.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.iq=function(){return!1};
g.k.wd=function(){return!1};
g.k.tE=function(){return!1};g.u(x3,g.X);g.k=x3.prototype;g.k.mt=function(){this.notification&&(this.B.stop(),this.Gb(this.u),this.u=null,this.notification.close(),this.notification=null)};
g.k.Xp=function(a){this.suggestion=a;p3(this,a,"hqdefault.jpg")};
g.k.HB=function(){g.YK(this,this.api.wd());this.api.Qa(this.element,this.api.wd());this.api.Qa(this.ha("ytp-upnext-autoplay-icon"),this.api.wd());this.cancelButton&&this.api.Qa(this.cancelButton.element,this.api.wd())};
g.k.dO=function(){window.focus();this.mt()};
g.k.yp=function(a){var b=this;this.Og()||(g.Do("a11y-announce","Up Next "+this.suggestion.title),this.l=(0,g.Q)(),this.i=new g.M(function(){y3(b,a)},25),y3(this,a),uHa(this.api,vHa(this,a)));
g.mn(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.X.prototype.hide.call(this)};
g.k.Og=function(){return!!this.i};
g.k.An=function(){this.vk();this.l=(0,g.Q)();y3(this);g.N(this.element,"ytp-upnext-autoplay-paused")};
g.k.vk=function(){this.Og()&&(this.i.dispose(),this.i=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(g.U(this.api.T().experiments,"autonav_notifications")&&a&&window.Notification&&document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(b=this.suggestion.Na(),this.mt(),this.notification=new Notification("Up Next",{body:b.title,icon:b.te()}),this.u=this.N(this.notification,"click",this.dO),this.B.start())}this.vk();this.api.nextVideo(!1,a)};
g.k.yJ=function(a){!g.Pe(this.cancelButton.element,g.Yo(a))&&g.xN(a,this.api)&&(this.api.wd()&&this.api.ub(this.ha("ytp-upnext-autoplay-icon")),this.select())};
g.k.xJ=function(){this.api.wd()&&this.cancelButton&&this.api.ub(this.cancelButton.element);g.QM(this.api,!0)};
g.k.QN=function(a){w3(this);this.show();this.yp(a)};
g.k.vH=function(a){w3(this);this.suggestion&&this.suggestion.Na().videoId===a.Na().videoId||this.Xp(a)};
g.k.RN=function(){w3(this);this.vk();this.hide()};
g.k.da=function(){this.vk();this.mt();g.X.prototype.da.call(this)};g.u(z3,v3);g.k=z3.prototype;g.k.create=function(){v3.prototype.create.call(this);this.B.N(this.player,"appresize",this.Ud);this.B.N(this.player,"onVideoAreaChange",this.Ud);this.B.N(this.player,"videodatachange",this.Oa);this.B.N(this.player,"autonavchange",this.IB);this.B.N(this.player,"autonavcancel",this.zJ);this.Oa()};
g.k.show=function(){v3.prototype.show.call(this);(this.I||this.u&&this.u!==this.videoData.clientPlaybackNonce)&&g.QM(this.player,!1);g.WM(this.player)&&this.iq()&&!this.u?(A3(this),2===this.videoData.autonavState?this.player.T().Z("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.yp():3===this.videoData.autonavState&&this.i.An()):(g.QM(this.player,!0),A3(this));this.Ud()};
g.k.hide=function(){v3.prototype.hide.call(this);this.i.An();A3(this)};
g.k.Ud=function(){var a=this.player.Vi(!0,this.player.isFullscreen());A3(this);this.l.Ud();g.O(this.element,"ytp-autonav-cancelled-small-mode",this.Le(a));g.O(this.element,"ytp-autonav-cancelled-tiny-mode",this.gu(a));g.O(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.mg(this.overlay.element,{width:a.width+"px"});if(!this.C){a=g.q(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){b=g.q(b.value);var c=b.next().value;b.next().value.Ud(1===c%2)}}};
g.k.Oa=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((this.suggestions=wHa(this,a))&&this.suggestions.length)for(this.i.Xp(this.suggestions[0]),this.i!==this.l&&this.l.Xp(this.suggestions[0]),a=0;a<BHa.length;++a){var b=BHa[a];if(this.suggestions&&this.suggestions[b]){this.videos[a]=new q3(this.player);var c=this.videos[a];b=this.suggestions[b];c.suggestion!==b&&(c.suggestion=b,p3(c,b));g.I(this,this.videos[a]);this.videos[a].fa(this.J.element)}}this.Ud()}};
g.k.IB=function(a){1===a?(this.I=!1,this.u=this.videoData.clientPlaybackNonce,this.i.vk(),this.ab&&this.Ud()):(this.I=!0,this.wd()&&(2===a?this.i.yp():3===a&&this.i.An()))};
g.k.zJ=function(a){a?this.IB(1):(this.u=null,this.I=!1)};
g.k.iq=function(){return 1!==this.videoData.autonavState};
g.k.Le=function(a){return(910>a.width||459>a.height)&&!this.gu(a)&&!(400>=a.width||360>=a.height)};
g.k.gu=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.wd=function(){return this.ab&&g.WM(this.player)&&this.iq()&&!this.u};
var BHa=[1,3,2,4];g.u(B3,v3);B3.prototype.wa=function(){var a=this.player.getVideoData();this.i.update({profilePicture:a.dg,author:a.author});this.subscribeButton.channelId=a.Bg;var b=this.subscribeButton;a.subscribed?b.l():b.u()};g.u(C3,g.X);C3.prototype.select=function(){(this.api.Ai(this.suggestion.Na().videoId,this.suggestion.Cd,this.suggestion.getPlaylistId(),void 0,void 0,this.suggestion.Ix||void 0)||this.api.Z("web_player_endscreen_double_log_fix_killswitch"))&&this.api.ub(this.element)};
C3.prototype.onClick=function(a){g.xN(a,this.api,this.l,this.suggestion.Cd||void 0)&&this.select()};
C3.prototype.u=function(a){switch(a.keyCode){case 13:case 32:g.cp(a)||(this.select(),g.bp(a))}};
C3.prototype.Oa=function(){var a=this.api.getVideoData(),b=this.api.T();this.l=a.C?!1:b.l};g.u(D3,v3);g.k=D3.prototype;g.k.create=function(){v3.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.suggestions=xHa(this,a),this.videoData=a);this.Ud();this.l.N(this.player,"appresize",this.Ud);this.l.N(this.player,"onVideoAreaChange",this.Ud);this.l.N(this.player,"videodatachange",this.Oa);this.l.N(this.player,"autonavchange",this.tw);this.l.N(this.player,"autonavcancel",this.AJ);a=this.videoData.autonavState;a!==this.L&&this.tw(a);this.l.N(this.element,"transitionend",this.qP)};
g.k.destroy=function(){g.Pt(this.l);g.Fi(this.stills);this.stills=[];this.suggestions=null;v3.prototype.destroy.call(this);g.mn(this.element,"ytp-show-tiles");this.I.stop();this.L=this.videoData.autonavState};
g.k.iq=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){v3.prototype.show.call(this);g.mn(this.element,"ytp-show-tiles");this.player.T().i?this.I.mg():this.I.start();(this.C||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.QM(this.player,!1);E3(this)?(F3(this),2===this.videoData.autonavState?this.player.T().Z("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.yp():3===this.videoData.autonavState&&this.i.An()):(g.QM(this.player,!0),F3(this))};
g.k.hide=function(){v3.prototype.hide.call(this);this.i.An();F3(this)};
g.k.qP=function(a){g.Yo(a)===this.element&&this.Ud()};
g.k.Ud=function(){if(this.suggestions&&this.suggestions.length){g.N(this.element,"ytp-endscreen-paginate");var a=this.G.Vi(!0,this.G.isFullscreen()),b=g.LM(this.G);b&&(b=b.ue()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),h=Math.max(a.height/54,2),l=this.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<h);){var p=b/2,r=e/2,t=b<=f-2&&n>=r*m,w=e<=h-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&w)n-=p*m,e+=2;else if(t)n-=
r*m,b+=2;else if(w)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.Dg(a,m,n);g.mg(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});this.i.Xp(this.suggestions[0]);this.i instanceof s3&&this.i.Ud();g.O(this.element,"ytp-endscreen-takeover",E3(this));F3(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(h=0;h<e;h++)if(p=c,r=0,d&&f>=b-2&&h>=e-2?
r=1:0===h%2&&0===f%2&&(2>h&&2>f?0===h&&0===f&&(r=2):r=2),p=g.fe(p+this.u,l),0!==r){t=this.stills[c];t||(t=new C3(this.player),this.stills[c]=t,a.appendChild(t.element));w=Math.floor(n*h/e);var x=Math.floor(m*f/b),y=Math.floor(n*(h+r)/e)-w-4,F=Math.floor(m*(f+r)/b)-x-4;g.ug(t.element,x,w);g.Dg(t.element,F,y);g.mg(t.element,"transitionDelay",(h+f)/20+"s");g.O(t.element,"ytp-videowall-still-mini",1===r);g.O(t.element,"ytp-videowall-still-large",2<r);r=t;p=this.suggestions[p];r.suggestion!==p&&(r.suggestion=
p,t=r.api.T(),w=g.kn(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",p3(r,p,w),g.PF(t)&&(t=p.rl(),t=g.Od(t,g.bO("emb_rel_end")),r.Ba("url",t)),(p=(p=p.Cd)&&p.itct)&&r.api.Tl(r.element,p));c++}g.O(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.Me(e.element),g.Ei(e);this.stills.length=c}};
g.k.Oa=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.u=0,this.suggestions=xHa(this,a),this.videoData=a,this.Ud())};
g.k.BJ=function(){this.u+=this.stills.length;this.Ud()};
g.k.CJ=function(){this.u-=this.stills.length;this.Ud()};
g.k.tE=function(){return this.i.Og()};
g.k.tw=function(a){1===a?(this.C=!1,this.B=this.videoData.clientPlaybackNonce,this.i.vk(),this.ab&&this.Ud()):(this.C=!0,this.ab&&E3(this)&&(2===a?this.i.yp():3===a&&this.i.An()))};
g.k.AJ=function(a){if(a){for(a=0;a<this.stills.length;a++)this.G.Qa(this.stills[a].element,!0);this.tw(1)}else this.B=null,this.C=!1;this.Ud()};
g.k.wd=function(){return this.ab&&E3(this)};g.u(G3,g.eN);g.k=G3.prototype;g.k.Hn=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!yHa(this.player)||b;var c=a.Zc||g.ZF(a.B),d=this.player.Jq();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.wd=function(){return this.endScreen.wd()};
g.k.TL=function(){return this.wd()?this.endScreen.tE():!1};
g.k.da=function(){this.player.Oe("endscreen");g.eN.prototype.da.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.DE;if(b&&b.videoId){var c=this.player.Ua().gd.get("heartbeat");a&&a.suggestions&&a.suggestions.length&&b.videoId===a.suggestions[0].id&&!a.eC?a=!1:(this.player.Ai(b.videoId,void 0,void 0,!0,!0,b),c&&c.nu("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0)}else a=!1;a||(g.eN.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.eN.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.zd=function(a){this.Hn()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.mf=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.Oa=function(){AHa(this);this.u&&zHa(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.i?this.endScreen=new z3(this.player):this.endScreen=new D3(this.player),g.I(this,this.endScreen),g.VM(this.player,this.endScreen.element,4))};g.kN.endscreen=G3;})(_yt_player);
